apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-server
  labels:
    app: server
spec:
  selector:
    matchLabels:
      app: server
  replicas: 1
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: syuvraj/grpc-server:v1
